export const SUPABASE_FILES_BUCKET = "blog-files";
export const SUPABASE_BLOGGER_TABLE = "bloggers"
export const SUPABASE_POST_TABLE = "posts"
export const SUPABASE_IMAGE_BUCKET = "blogger-images"
export const SUPABASE_UPVOTES_TABLE = "upvotes"
export const LIMIT = 3;
export const TITLE_LENGTH = 50;
export const DESCRIPTION_LENGTH = 100;
export const PHOTO_LIMIT = 10;
export const SEARCH_UPVOTED_POSTS_FUNCTION = "search_upvoted_post_by_single_user"
export const FILE_CHANGE_LIMIT = 5
export const ALLOWED_LANGUAGES = ["python", "javascript", "rust"] as const