const markdownArray = [
    "---",
    "title: \"About rce-blog\"",
    "description: \"A little explainer about this website\"",
    "language: \"python\"",
    "--- ",
    "",
    "## Motivation",
    "Taking programming notes is hard. Till now, I've been using VsCode which provides a nice ",
    "experience when writing code. But, what if you want to write text? You can use comments. ",
    "But, what if ",
    "- You want to add images?",
    "- You want a canvas on which you can draw free hand drawings",
    "and diagrams to illustrate concepts visually?",
    "- You want to write in LaTeX",
    "- You want to see those notes from anywhere on any device?",
    "- You want to share them if you have written something that can be useful for someone?",
    "  ",
    "Maybe a tool that does all these exists but I decided to build one for myself, tailored to my needs.",
    "Couple of months ago, I started making it for a general user and allowing anyone to write and share ",
    "posts like the one you are reading right now. Keep on reading to learn what's so special about writing on this website.",
    "",
    "## Demo",
    "",
    "Let me first demo the feature which was the main motivation behind building this - ",
    "_Remote Code Execution_. You can write posts with code-snippets which are editable and executable",
    "for you and your readers (in case you make your post public).",
    "",
    "Click on `</>` button on your screens (on the right or bottom of your screen depending on your device",
    ") and wait for it to turn green.",
    "",
    "```python",
    "",
    "a = \"hello\"",
    "b = \"world\"",
    "",
    "print(\"a+b ->\", a+\" \"+b)",
    "```",
    "",
    "Run the above code snippet either by hitting `Shift-Enter`, double-clicking on the snippet or clicking the run button on top",
    "right of the code block (first button from the left). You should see the correct output. Now try editing it! Replace the code in above block",
    "with any python code and try running it.",
    "",
    "### Same Context",
    "",
    "Here's another snippet",
    "",
    "```",
    "c = a + \" \" + b",
    "print(\"c ->\", c)",
    "```",
    "This code block runs in the same context as the previous one and therefore \"_knows_\" what `a` and ",
    "`b` are. All the code blocks in a post run in the same context (unless specified otherwise).",
    "",
    "",
    "### On run-code",
    "",
    "When you click run-code on a block:",
    "",
    "1. All the code inside all the blocks till and including that block is",
    "   collected and sent to the server.",
    "3. The server writes that code to a file named `file` (I'm a genius), executes the file and sends",
    "   it's output back to you.",
    "",
    "If you want to execute some code in a different file just append `file-[filename]` comment at the ",
    "top of a code block. The code in that code block and subsequent code blocks will run inside the file you ",
    "mentioned in the comment. Here's a demo:",
    "",
    "```python",
    "#file-other",
    "",
    "d = c",
    "print(d)",
    "```",
    "",
    "This code snippet runs in file `other.py` and therefore should throw an error because it doesn't",
    "know what `c` is. ",
    "",
    "*Exercise to the reader* - Try importing `c` from `file.py` and running this code again!!",
    "",
    "### Shell",
    "",
    "When you activate remote code execution, you are provided with a Linux environment. It is your",
    "birthright to be able to interact with it. You can do so by clicking on Shell icon in top-right",
    "(second icon from the left). This will open up a textarea in which you can write shell ",
    "commands and execute them by hitting `Enter` or clicking on run button on the right.",
    "",
    "> Note - Subsequent shell commands are stateless i.e.",
    "commands that change the state of the shell won't work as expected (for eg `cd ..` ",
    "will not set parent directory as current directory). ",
    "",
    "Try running `ls -l src` below after opening the shell textarea. ",
    "",
    "```",
    "```",
    "",
    "## About Website",
    "",
    "The post which you are reading right now is built from a simple markdown file. Any writer would",
    "just need to mention his post's title, description and language for that",
    "post's code blocks (one of python,rust or javascript) on top of his markdown file as shown below.",
    "![Post Metadata](carbon.png)",
    "",
    "You can start writing posts like this by going to [Write](https://rce-blog.xyz/edit) page. ",
    "Write page has helpers for making writing in markdown easier for anyone who hasn't done it before.",
    "All your posts will be private by default which you can then choose to make public (or not).",
    "",
    "### Pages",
    "#### Home page",
    "",
    "Home page shows most recently uploaded posts (for now) and a search bar. Search indexes over ",
    "every post's title, decription, language and author's name.",
    "This enables you to enter queries like",
    "",
    "_How prototypes work in javascript by John Carmack_.",
    "",
    "The search results not only contain the public posts which satisfy your query but also _your_ private",
    "posts (if there are any which match with query). This isn't a bug but a feature i.e any user can",
    "search all the public posts and _only her_ private posts directly from the home page.",
    "",
    "#### Profile page",
    "",
    "Your profile page will contain all your public, private, most upvoted posts and posts upvoted by",
    "you. You or any visitor to your page will be able to search your posts or posts upvoted by you ",
    "exclusively. ",
    "",
    "This is what my profile page looks like on all screens",
    "![desktop view, tablet view, mobile view](desktop.PNG,tablet.PNG,phone.jpg)",
    "",
    "(Subtle way of conveying that the website is responsive and has support for carousels)",
    "",
    "#### Write Page",
    "",
    "This post is written on the **Write** page of the website. You have the option to add posts by",
    "uploading a markdown file but I highly recommend creating any new posts from the Write page.",
    "Not only it has some helper features which will make writing in markdown accessible to anyone who hasn't done it ",
    "before, but also some cool features/gimmicks which I'll talk about shortly.",
    "",
    "",
    "### Bells and Whistles",
    "",
    "#### Whiteboard",
    "Get a white board anywhere you want while writing your post which can be used to draw free hand drawings",
    "and diagrams. It is no Procreate but I'll continue improving it over time. Just write `canvas{number}`",
    "anywhere in your markdown and click preview to start drawing on the canvas. ",
    "",
    "![write canvas{number} anywhere in the document,start drawing free hand drawings](1.png,2.png)",
    "",
    "Below is an example of what canvas looks like to a reader.",
    "",
    "canvas1",
    "",
    "#### Images and carousels",
    "",
    "This is a feature you've seen already, but using this as an excuse to show you some of my scenic clicks in midst of this ",
    "boring post.",
    "![snowladen hills of manali, Solang Valley, Kasol, Kasol Park, On top of George Everest](manali.jpg,solang-valley.jpg,kasol.jpg,kasol-park.jpg,george-everest.jpg)",
    "",
    "`![caption][image_name]` would display a single image.",
    "",
    "`![caption1,caption2,caption3](image1,image2,image3)` would display a carousel of 3 images. Carousels",
    "can have upto 6 images.",
    "",
    "",
    "",
    "",
    "##### Don't have an image? Generate one",
    "",
    "Just type in `![your imaginative caption here]()` in markdown on the **Write** page and let ",
    "AI do the magic for you. Ever wondered how Elon Musk would look like as a warrior?",
    "",
    "![elon musk as a warrior]()",
    "",
    "#### LaTeX support for math nerds",
    "",
    "Write math equations in LaTeX without making your post look ugly. Here's one of ",
    "the most beautiful ones:",
    "",
    "_Euler's identity -_ `$e^{i \\pi} + 1 = 0$`",
    "",
    "#### Youtube Links Miniplayer",
    "",
    "YouTube links will render in the miniplayer _if_ you don't provide an alt text for them. Normal",
    "share links with arbitrary starting times will work (no need to get an embed link from YouTube webapp).",
    "",
    "[](https://youtu.be/dQw4w9WgXcQ?t=43)",
    "",
    "## Future Plans",
    "",
    "There's a huge scope of improvement on this website. ",
    "",
    "- Code Editor can be improved. (vim support is top priority)",
    "- Support for many more languages (Currently supports `python`,`javascript` and `rust`).",
    "- Whiteboard can be improved.",
    "- Allowing you more freedom in writing posts by supporting MDX.",
    "- Prettier design. (All the design on this website is done solely by a noob with",
    "  pretty bad aesthetic sense, so there's a huge scope for improvement in this area)",
    "- Adding grammar checks so don't write sentences like this you (this seems easy, GPT-3 will",
    "  help)",
    "",
    "The list goes on and on. I'll continue working on it for the foreseeable future.",
    ""
]


export default markdownArray